[features]
seeds = false
[programs.localnet]
puppet = "HttxV1yGBtm4gwouBqoG7BhPu2nj4N74KfsE2ZDnMyeo"
puppet_master = "2Uog4wX8X4Dzj9bZL7S1im8QrRQRGW2gZNNXVcjGTAig"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/bmstart/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
